apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PrivilegedContainers
metadata:
  name: psp-privileged-container
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
