apiVersion: v1
kind: Pod
metadata:
  labels:
    run: privileged
  name: privileged
spec:
  containers:
  - image: busybox
    name: privileged
    command: ['sh', '-c', 'sleep 99999']
    securityContext:
       privileged: true
