apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: ns-must-have-gk
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    scope: "Namespaced"
    namespaces:
      - "tenant"
  parameters:
    labels: 
    - {{ .Values.constraint.label }}
