apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PrivilegedContainers
metadata:
  name: privileged-container
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "tenant"
      
