apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNamespacePSS
metadata:
  name: namespace-must-have-pss-labels
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:

