apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-hostpath
spec:
  allowedHostPaths:
    - pathPrefix: "/foo"
      # readOnly: false
  privileged: false
  allowPrivilegeEscalation: false
  hostNetwork: false
  hostPID: false
  hostIPC: false
  seLinux: { 'rule': 'RunAsAny' }
  runAsUser: { 'rule': 'RunAsAny' }
  fsGroup: { 'rule': 'RunAsAny' }
  supplementalGroups: { 'rule': 'RunAsAny' }
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    # Assume that ephemeral CSI drivers & persistentVolumes set up by the cluster admin are safe to use.
    - 'csi'
    - 'persistentVolumeClaim'
    - 'ephemeral'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-hostpath
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - psp-hostpath

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-hostpath
roleRef:
  kind: ClusterRole
  name: cr-hostpath
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: sa-hostpath
  namespace: developers

