---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: egress-deny-default
spec:
  order: 3000 # if it is 1000 or less, knp can't override this "default" rule
  egress:
    - action: Deny
