apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 99999
    livenessProbe:
      exec:
        command:
        - "/bin/sh"
        - "-c"
        - "whoami > /root/whoami.txt && ps -ef > /root/ps.txt && ls /var/lib > /root/ls.txt"
      initialDelaySeconds: 5
      periodSeconds: 5

