kind: k8sRequiredFields
apiVersion: constraints.gatekeeper.sh/v1beta1
metadata:
  name: required-annotation-owner
spec:
  enforcementAction: enforce
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
    # scope: "Namespaced"
    # namespaces:
    #   - "tenant"
  # Use match for kinds and namespaces
  # to set where the constraint is enforced
  
  parameters:
    # What objects get validated
    selectorFields:
    - path: "spec.type"
      value: "NodePort"
    namespaces:
    - "*"
    exemptions:
    - namespace: "platform"
      resources:
      - "metrics"

    # What validation is required from objects
    attributeRequirements:
    - path: ["metadata","annotations", "owner"]
      operation: "IS"
      value: "system"

    # Message for violations
    message: "Service type nodeport (except metrics in namespace platform) must have annotation 'owner' of 'system'."
