---
repositories:
  - name: falcosecurity
    url: https://falcosecurity.github.io/charts

releases:

  - name: falco
    chart: falcosecurity/falco
    namespace: falco
    createNamespace: true
    installed: true
    wait: true
    waitForJobs: true
    version: "1.17.3"
    # Latest chart 1.19.2 doesn't work on this version of the ISO minikube uses
    values:
    - ./falco/values.yaml
